app:
    resource: "@AppBundle/Controller/"
    type:     annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
_user_bundle:
    resource: "@AppBundle/Resources/config/routing.yml"